import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Privacy Policy",
    description: "DealRoom AI Privacy Policy — how we collect, use, and protect your data.",
};

const SECTIONS = [
    {
        title: "1. Information We Collect",
        content: `When you use DealRoom AI, we may collect the following information:
• **Account Information:** Name, email address, and billing details when you create an account or purchase a plan.
• **Usage Data:** Information about how you interact with our platform, including companies analyzed, reports generated, and feature usage patterns.
• **Payment Data:** Payment information is processed securely through our payment partner (PayU). We do not store your full credit card or bank details on our servers.
• **Technical Data:** IP address, browser type, device information, and cookies for analytics and service improvement.`,
    },
    {
        title: "2. How We Use Your Data",
        content: `We use the collected information to:
• Provide, operate, and maintain the DealRoom AI platform.
• Process payments and manage your subscription.
• Generate M&A intelligence reports using our AI agent pipeline.
• Improve our services, algorithms, and user experience.
• Communicate with you about updates, security alerts, and support.
• Comply with legal obligations and enforce our terms.`,
    },
    {
        title: "3. Data Sources & AI Agents",
        content: `DealRoom AI deploys autonomous web research agents that collect publicly available information from sources including SEC EDGAR, PACER court records, USPTO patent databases, LinkedIn (public profiles), Google News, and other publicly accessible data.

We do not scrape private or restricted data. All information gathered by our agents is publicly available. Reports are generated by synthesizing this public data using Google Gemini AI models.`,
    },
    {
        title: "4. Data Sharing & Third Parties",
        content: `We do not sell your personal information. We may share data with:
• **Service Providers:** TinyFish (AI agent execution), Google Cloud (Gemini AI synthesis), Neon (database hosting), and PayU (payment processing).
• **Legal Requirements:** When required by law, subpoena, or court order.
• **Business Transfers:** In the event of a merger, acquisition, or asset sale, user data may be transferred as part of the transaction.`,
    },
    {
        title: "5. Data Security",
        content: `We implement industry-standard security measures to protect your data:
• All data in transit is encrypted using TLS 1.3.
• API keys and credentials are stored securely in environment variables, never in client-side code.
• Database connections use SSL/TLS encryption.
• We conduct regular security reviews of our codebase and infrastructure.`,
    },
    {
        title: "6. Data Retention",
        content: `• **Reports:** Generated reports are stored for the duration specified by your plan (7 days for Starter, unlimited for Pro and Enterprise).
• **Account Data:** Retained for as long as your account is active. Upon deletion request, we remove your data within 30 days.
• **Usage Analytics:** Anonymized analytics data may be retained indefinitely for service improvement.`,
    },
    {
        title: "7. Your Rights",
        content: `Depending on your jurisdiction, you may have the right to:
• Access, correct, or delete your personal data.
• Opt out of marketing communications.
• Request a copy of your data in a portable format.
• Lodge a complaint with a data protection authority.

To exercise any of these rights, contact us at privacy@dealroom.ai.`,
    },
    {
        title: "8. Cookies",
        content: `We use essential cookies to maintain your session and preferences. We may also use analytics cookies (such as Google Analytics) to understand usage patterns. You can control cookie preferences through your browser settings.`,
    },
    {
        title: "9. Changes to This Policy",
        content: `We may update this Privacy Policy from time to time. We will notify you of significant changes via email or a prominent notice on our platform. Continued use of DealRoom AI after changes constitutes acceptance of the updated policy.`,
    },
    {
        title: "10. Contact Us",
        content: `If you have questions or concerns about this Privacy Policy, please contact us at:
• **Email:** privacy@dealroom.ai
• **Address:** DealRoom AI, San Francisco, CA, USA`,
    },
];

export default function PrivacyPage() {
    return (
        <div style={{ maxWidth: 800, margin: "0 auto", padding: "80px 32px" }}>
            <div style={{ textAlign: "center", marginBottom: 48 }}>
                <span className="badge badge-violet anim-fade-up" style={{ marginBottom: 14 }}>Legal</span>
                <h1 className="anim-fade-up delay-1" style={{ fontSize: "clamp(32px,5vw,48px)", fontWeight: 900, letterSpacing: "-2px", marginTop: 12 }}>
                    Privacy <span className="gradient-text">Policy</span>
                </h1>
                <p className="anim-fade-up delay-2" style={{ color: "var(--text-muted)", fontSize: 14, marginTop: 12 }}>
                    Last updated: March 8, 2026
                </p>
            </div>

            <div className="glass-card anim-fade-up delay-2" style={{ padding: "40px 36px", opacity: 0 }}>
                <p style={{ color: "var(--text-secondary)", fontSize: 15, lineHeight: 1.8, marginBottom: 32 }}>
                    At DealRoom AI, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our autonomous M&amp;A intelligence platform.
                </p>

                {SECTIONS.map((section, i) => (
                    <div key={i} style={{ marginBottom: 32 }}>
                        <h2 style={{ fontSize: 18, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12 }}>{section.title}</h2>
                        <div style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.8, whiteSpace: "pre-line" }}>
                            {section.content}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
